services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: phucthanh2002/dockerncicd:latest
    container_name: phucthanh_app
    ports:
      - "8080:8080"
    restart: always
    environment:
      - SPRING_PROFILES_ACTIVE=prod
